name: ðŸš€ Deploy website on push
on:
  push:
    branches: [main]

jobs:
  FTP-Deploy-Action:
      name: ðŸŽ‰ FTP-Deploy-Action
      runs-on: ubuntu-latest
      steps:
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: ðŸ“‚ FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          ftp_server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
